/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/Extend/Child.vue')['default']
    Child2: typeof import('./src/components/Props/Child2.vue')['default']
    Child3: typeof import('./src/components/Props/Child3.vue')['default']
    Child4: typeof import('./src/components/Props/Child4.vue')['default']
    Directive: typeof import('./src/components/Directive/index.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    EnableKeyboard: typeof import('./src/components/Directive/EnableKeyboard.vue')['default']
    Extend: typeof import('./src/components/Extend/index.vue')['default']
    'Index.story': typeof import('./src/components/Index.story.vue')['default']
    PermissionControl: typeof import('./src/components/Directive/PermissionControl.vue')['default']
    Props: typeof import('./src/components/Props/index.vue')['default']
    SortableDrag: typeof import('./src/components/Directive/SortableDrag.vue')['default']
    TableScroll: typeof import('./src/components/Directive/TableScroll.vue')['default']
    VxeTable: typeof import('./src/components/VxeTable/index.vue')['default']
    VxeTableDemo: typeof import('./src/components/VxeTableDemo/index.vue')['default']
    VxeTableFilter: typeof import('./src/components/VxeTableFilter/index.vue')['default']
    VxeTablePlus: typeof import('./src/components/VxeTablePlus/index.vue')['default']
  }
}
