/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/Extend/Child.vue')['default']
    Child2: typeof import('./src/components/Props/Child2.vue')['default']
    Child3: typeof import('./src/components/Props/Child3.vue')['default']
    Child4: typeof import('./src/components/Props/Child4.vue')['default']
    Directive: typeof import('./src/components/Directive/index.vue')['default']
    EnableKeyboard: typeof import('./src/components/Directive/EnableKeyboard.vue')['default']
    Extend: typeof import('./src/components/Extend/index.vue')['default']
    'Index.story': typeof import('./src/components/Index.story.vue')['default']
    PermissionControl: typeof import('./src/components/Directive/PermissionControl.vue')['default']
    Props: typeof import('./src/components/Props/index.vue')['default']
    SortableDrag: typeof import('./src/components/Directive/SortableDrag.vue')['default']
    TableScroll: typeof import('./src/components/Directive/TableScroll.vue')['default']
  }
}
