/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BigScreen: typeof import('./../components/BigScreen/index.vue')['default']
    Child: typeof import('./../components/Props/Child.vue')['default']
    Directive: typeof import('./../components/Directive/index.vue')['default']
    EnableKeyboard: typeof import('./../components/Directive/EnableKeyboard.vue')['default']
    'Index.story': typeof import('./../components/Index.story.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDialog: typeof import('naive-ui')['NDialog']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PermissionControl: typeof import('./../components/Directive/PermissionControl.vue')['default']
    Props: typeof import('./../components/Props/index.vue')['default']
  }
}
